apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-svc
  labels:
    app: nginx
    environment: development
    type: webserver
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    environment: development
