apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
    environment: development
    type: webserver
    tier: backend
spec:
  type: NodePort
  ports:
  - nodePort: 30001
    port: 80
    targetPort: 80
  selector:
    app: nginx
    environment: development
    type: webserver
    tier: backend