apiVersion: v1
kind: Pod
metadata:
  labels:
    app: test
  name: redis-pod
spec:
  containers:
  - image: redis:alpine
    name: redis
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
    
