apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    app: nginx
    environment: development
    type: webserver
spec:
  template:
    metadata:
      labels:
        app: nginx
        environment: development
        type: webserver
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      environment: development
      type: webserver
