apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    app: nginx
    environment: development
    type: webserver
spec:
  template:
    metadata:
      labels:
        app: nginx
        environment: development
        type: webserver
        tier: backend
    spec:
      containers:
      - name: nginx-container
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      environment: development
      type: webserver
      tier: backend
